# Created with https://github.com/marketplace/actions/create-a-release

on:
  push:
    # Sequence of patterns matched against refs/tags
#    branches:
#      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # https://github.community/t/accessing-commit-message-in-pull-request-event/17158/8
#      - name: get commit message
#        run: |
#          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
#      - name: show commit message
#        run: echo $commitmsg
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # https://stackoverflow.com/questions/63619329/github-action-get-commit-message
#          tag_name: ${{ github.event.head_commit.message }}
#          release_name: ${{ github.event.head_commit.message }}
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            See [CHANGES.md](https://github.com/holgerbrandl/krangl/blob/master/CHANGES.md) for new features, bug-fixes and changes.
          draft: false
          prerelease: false